### ISSUE TITLE
서버에서 유저 퀴즈 조회 관련 질문

### ISSUE THREAD

**Issue by HeegeePark** [HeegeePark/GuessMe_iOS#54]
## 문제 상황
- 호준스 피드백 기반으로 퀴즈 생성 POST(createQuiz)를 수정한 후, test2라는 계정을 만들고, 퀴즈 생성함. 앱 화면에서는 성공적으로 생성했다고 알럿이 뜨긴 함.
- PostMan으로 제대로 작동하는지 검증 시도
  - test 계정으로 로그인한 후, `/quizzes/{test2}`에 GET 요청을 시도
  - **하지만**, 앱에서 생성했던 퀴즈의 content, answer 다 다름.
  - 아래 사진은 시도 결과
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/47033052/174672194-3a516fea-2fb9-49ca-9d94-b0d484f27232.png">

## 여기서 궁금한 점
- 퀴즈 생성 POST가 제대로 되지 않았다면, 유저 퀴즈 조회 GET 요청 시 해당 유저는 퀴즈가 없으니 에러가 떠야하는거 아닌가요?
- 근데 아예 다른 퀴즈가 불러와져서 왜 그러한지 궁금합니다. 서버 문제(?)일 수도 있나 싶어서요..!

**Comment by HeegeePark** [comment]
내가 잘못 이해하고 있는 부분도 있다면, 알려주세요~!!!

**Comment by YouHojoon** [comment]
# content 다른 문제

```swift
class Api{

   public func getQuizzes(type: QuizType) -> Single<[Quiz]> {
                                               ...중략...
     let quiz = Quiz(quizId: count, content: item["content"]!.stringValue, answer: item["answer"]!.intValue)
     count += 1
   }
}
```

Api getQuizzes 메소드에서 quizId를 count로 넣으니까 아예 다른 퀴즈가 불러와지는거야!

---

# answer 다른 문제


```swift
class QuizViewModel{

   private func selectAnswer(item: Quiz, selected: Int) {
     _ = self.input.quizObservable
            .map { quizzes in
                quizzes.map { q in
                    if q.quizId == item.quizId {
                        print("선택: \(selected)")
                        return Quiz(quizId: q.quizId, content: q.content, answer: selected)
                    } else {
                        return Quiz(quizId: q.quizId, content: q.content, answer: q.answer)
                    }
      }
    }
  }
}
```
input.quizObservable 기준으로 output.quizObservable이 바뀌는거면 input.quizObservable도 바꿔줘야돼
input이 최신화가 안되서 마지막으로 선택한 answer하나만 반영되고있어

## Test
![image](https://user-images.githubusercontent.com/53998480/174699311-c79a572e-ed0e-4f30-8b02-6df2c7205391.png)
### output.quizObservable
`
[GuessMe_iOS.Quiz(quizId: 1, content: "샤워하고 나와서 자아도취 해봤다.", answer: 0), GuessMe_iOS.Quiz(quizId: 2, content: "발을 헛디뎌 놓고 아무렇지 않은 척 걸어간 적 있다.", answer: 0), GuessMe_iOS.Quiz(quizId: 3, content: "술 마시고 지하철 역/버스정류장 잘못내린 적 있다.", answer: 0), GuessMe_iOS.Quiz(quizId: 4, content: "술 마시고 전 애인한테 전화해봤다.", answer: 0), GuessMe_iOS.Quiz(quizId: 5, content: "술 마시고 지하철 종점 찍은 적이 있다.", answer: 1)]
`

**Comment by HeegeePark** [comment]
이해 쏙쏙되는 답변 감사합니다!
#55 에서 기존 PR에서의 문제점과 여기서 호준스가 언급한 문제점 다 해결해서 커밋했으요!
- [content 해결](https://github.com/HeegeePark/GuessMe_iOS/pull/55/commits/3069fc7c791044979e39f9f16955ff2de3048213)
- [answer 해결](https://github.com/HeegeePark/GuessMe_iOS/pull/55/commits/510efac846b1e72c98111ffc26136caa1e649b35)
